name: CD
on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "src/**"
      - "tests/**"
    types:
      - closed
jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync

      - name: Display Python version
        run: uv run python -c "import sys; print(sys.version); print(sys.executable); print(sys.path)"

      - name: Build
        run: uv build

      - name: Publish to TestPypi
        run: uv publish --publish-url https://test.pypi.org/legacy/
