name: CI
on:
  pull_request:
    paths:
      - "src/**"
      - "test/**"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run unittest
        run: python -m unittest discover -v -s ./tests/
